### ISSUE TITLE
identitystore.list_users is not return all the users from the aws

### ISSUE THREAD

**Issue by somakorimi** [ooiyeefei/aws-iam-identity-center-permission-policies-analyzer#8]
in dataExtractionFunction handler.py is not returning all the users from the aws
 user_list_response = identitystore.list_users(
        IdentityStoreId=IDENTITY_STORE_ID

where if I use from cli: aws identitystore list-users --identity-store-id d-xxxxx007ax its able to pull all the user list.

**Comment by somakorimi** [comment]
this is because of pagination is not considered while getting list_users

**Comment by huangz27** [comment]
Hello, thank you for highlighting this issue! We have fixed the code to now consider pagination for list_user in this new PR #9, it should work now!
